/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class camerademo_OpenCVHelper */

#ifndef _Included_camerademo_OpenCVHelper
#define _Included_camerademo_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     camerademo_OpenCVHelper
 * Method:    Checkedge
 * Signature: ([III)[I
 */
JNIEXPORT void JNICALL Java_camerademo_OpenCVHelper_Checkedge
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

/*
 * Class:     camerademo_OpenCVHelper
 * Method:    Cut
 * Signature: ([III[I)[I
 */
JNIEXPORT jintArray JNICALL Java_camerademo_OpenCVHelper_Cut
  (JNIEnv *, jclass, jintArray,jintArray, jint, jint,jintArray);

JNIEXPORT jintArray JNICALL Java_camerademo_OpenCVHelper_Rect
        (JNIEnv *, jclass, jintArray,jintArray,jint,jint);
#ifdef __cplusplus
}
#endif
#endif
